# Generated by Django 3.1 on 2021-02-26 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetACLPolicy',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('policy_type', models.CharField(choices=[('assetACL', 'AssetACL')], max_length=32, verbose_name='Policy Type')),
                ('action', models.IntegerField(choices=[(1, 'Deny'), (2, 'Confirm')], default=1, verbose_name='Action')),
                ('created_by', models.CharField(blank=True, max_length=128, verbose_name='Created by')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('user', models.CharField(max_length=128, verbose_name='User')),
                ('ip_start', models.GenericIPAddressField(verbose_name='IP Start')),
                ('ip_end', models.GenericIPAddressField(verbose_name='IP End')),
                ('port', models.IntegerField(default=22, verbose_name='Port')),
                ('system_user', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_@\\-\\.]*$', 'Special char not allowed')], verbose_name='System User')),
                ('need_review', models.BooleanField(default=False, verbose_name='need review')),
                ('reviewers', models.ManyToManyField(related_name='assetaclpolicys', to=settings.AUTH_USER_MODEL, verbose_name='Reviewers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
